### ISSUE TITLE
PyTorch and Tensorflow dataset compatibility

### ISSUE THREAD

**Issue by blaiszik** [MLMI2-CSSI/foundry#29]
* Add capabilities to map Foundry datasets to PyTorch or Tensorflow datasets. 
* Ensure we are capturing enough metadata to make this possible.

### PyTorch
https://pytorch.org/tutorials/beginner/data_loading_tutorial.html

### Tensorflow
https://www.tensorflow.org/datasets

**Comment by Aadit-Ambadkar** [comment]
The problem here (from what I can see) is that Foundry Datasets have little regulation surrounding them. When I run `res = f.load_data()`, I get back a dictionary that is guaranteed to have a 'train' key. But when I access `res['train']`, I can get back a tuple, a dictionary, and possibly other objects. For it to be possible to map a foundry dataset to PyTorch or TF, we would need to standardize the way in which datasets are formated. So, for instance, requiring the structure to be as follows:
```json
{
    "train": {
        "input-type-1": [
            "input1",
            "input2",
            "input3",
            etc
        ],
        "input-type-2": [
            "input1",
            "input2",
            "input3",
            etc
        ],
        etc,
        "target": [
            "target1",
            "target2",
            "target3",
            etc
        ]
    }
}
```

**Comment by Aadit-Ambadkar** [comment]
Ok, so the above problem has (partially) been resolved, so I can guarantee that I'm either getting hdf5 formatted datasets or foundry datasets. I'll be handling hdf5 first, and then foundry. I'll focus on pytorch now (as I am more familiar with that) and once I get pytorch to work, I'll be workint on tenorflow.

**Comment by Aadit-Ambadkar** [comment]
This was merged!
