### ISSUE TITLE
Mismatch between requirements used in tests, and installed via PyPI

### ISSUE THREAD

**Issue by WardLT** [MLMI2-CSSI/foundry#303]
**Is your feature request related to a problem? Please describe.**
`v0.5.0` did not install joblib when you installed it with pip.

We missed this in our tests because joblib is installed alongside sklearn when our tests use requirements.txt to build the environment, but not installed using the dependencies in setup.py

**Describe the solution you'd like**
Switch to a single file for package description, pyproject.toml

**Describe alternatives you've considered**
- Have setup.py read from requirements.txt. That's just mimicking behavior that pyproject.toml would do with our own custom code.

**Additional context**
Should not be relevant now, as we dropped joblib. But, we should be aware of this potential issue in the future until we harmonize our requirements.

**Comment by ascourtas** [comment]
Update: I still get the joblib error on fresh installs, not sure if that's because we haven't released in a while though? something to keep an eye on 

Also, I disagree that setup.py should mirror requirements.txt per Python guidelines https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/#install-requires-vs-requirements-files

**Comment by WardLT** [comment]
That's a great explainer on setup.py compared to requirements.txt. thanks, Ari!

**Comment by WardLT** [comment]
I'm still not certain we need the "minimal" install and the full environment for this project to be different. What do you think?
